// TOEIC700 word list, 250 words
window.wordData = [
  { id: "a001", word: "accommodate", meaning: "収容する", example: "This conference room can accommodate up to 50 people." },
  { id: "a002", word: "accompany", meaning: "同行する", example: "Ms. Tanaka will accompany the CEO on his trip to London." },
  { id: "a003", word: "accounting", meaning: "経理", example: "He works in the accounting department of a large corporation." },
  { id: "a004", word: "acquisition", meaning: "買収", example: "The tech giant announced its acquisition of a smaller startup company." },
  { id: "a005", word: "actually", meaning: "実際に", example: "We thought the project was finished, but actually there are still two tasks left." },
  { id: "a006", word: "additional", meaning: "追加の", example: "Please contact us if you need any additional information about the product." },
  { id: "a007", word: "address", meaning: "対処する", example: "We need to address the customer's complaint as soon as possible." },
  { id: "a008", word: "administration", meaning: "管理", example: "She works in university administration, handling student records." },
  { id: "a009", word: "admit", meaning: "認める", example: "He admitted that he made a mistake in the financial report." },
  { id: "a010", word: "advance", meaning: "進める", example: "They decided to advance the meeting date by one week to discuss the issue sooner." },
  { id: "a011", word: "advertising", meaning: "広告", example: "Our team is developing a new advertising campaign for the spring product launch." },
  { id: "a012", word: "afford", meaning: "〜する余裕がある", example: "I can't afford to buy a new car on my current salary." },
  { id: "a013", word: "agenda", meaning: "議題", example: "Let's move on to the next item on the meeting agenda." },
  { id: "a014", word: "allocate", meaning: "割り当てる", example: "The project manager will allocate tasks to each team member." },
  { id: "a015", word: "allow", meaning: "許可する", example: "Employees are not allowed to use their phones during meetings." },
  { id: "a016", word: "analyst", meaning: "分析者", example: "She works as a financial analyst at an investment firm." },
  { id: "a017", word: "analyze", meaning: "分析する", example: "We need to analyze last quarter's sales data to plan for the next quarter." },
  { id: "a018", word: "annual", meaning: "年に1度の", example: "Our company holds an annual conference for all the regional managers." },
  { id: "a019", word: "appear", meaning: "現れる", example: "It appears that our sales have increased this quarter." },
  { id: "a020", word: "appliance", meaning: "器具", example: "Our new apartment has modern kitchen appliances such as a microwave and dishwasher." },
  { id: "a021", word: "applicant", meaning: "応募者", example: "Each job applicant must submit a résumé and cover letter." },
  { id: "a022", word: "apply", meaning: "申し込む", example: "I plan to apply for the management training program next year." },
  { id: "a023", word: "appointment", meaning: "予約", example: "I have a doctor's appointment at 10 AM tomorrow." },
  { id: "a024", word: "appreciate", meaning: "感謝する", example: "I really appreciate your help with the project." },
  { id: "a025", word: "appropriately", meaning: "適切に", example: "Please dress appropriately for the job interview." },
  { id: "a026", word: "approximately", meaning: "おおよそ", example: "The meeting will last approximately two hours." },
  { id: "a027", word: "architect", meaning: "建築家", example: "The famous architect designed the new city hall building." },
  { id: "a028", word: "aspect", meaning: "側面", example: "Safety is an important aspect of our product design." },
  { id: "a029", word: "assess", meaning: "評価する", example: "The manager will assess the performance of each employee at the end of the quarter." },
  { id: "a030", word: "assignment", meaning: "任務", example: "Our assignment is to create a marketing plan for a new product." },
  { id: "a031", word: "assume", meaning: "仮定する", example: "I assumed that the office was closed on weekends, but it's actually open." },
  { id: "a032", word: "attend", meaning: "出席する", example: "Over 200 people attended the international conference last year." },
  { id: "a033", word: "attendance", meaning: "出席", example: "Attendance at the weekly meeting is mandatory for all staff." },
  { id: "a034", word: "attract", meaning: "引き付ける", example: "The new restaurant is trying to attract customers with a special discount." },
  { id: "a035", word: "auditorium", meaning: "講堂", example: "The speech will be held in the auditorium at 4 PM." },
  { id: "a036", word: "benefit", meaning: "利益", example: "One benefit of this job is the flexible working hours." },
  { id: "a037", word: "bid", meaning: "入札", example: "Several construction companies are bidding for the highway project contract." },
  { id: "a038", word: "branch", meaning: "支店", example: "Our company opened a new branch in Osaka last month." },
  { id: "a039", word: "brochure", meaning: "パンフレット", example: "The travel agency's brochure has details of their tour packages." },
  { id: "a040", word: "budget", meaning: "予算", example: "We need to reduce our marketing budget for next year." },
  { id: "a041", word: "candidate", meaning: "候補者", example: "There were five qualified candidates interviewed for the position." },
  { id: "a042", word: "cardboard", meaning: "段ボール", example: "Please put those cardboard boxes in the recycling bin." },
  { id: "a043", word: "cater", meaning: "料理を提供する", example: "We hired a local company to cater our office holiday party." },
  { id: "a044", word: "certify", meaning: "証明する", example: "The auditor will certify the financial statements as accurate." },
  { id: "a045", word: "checkup", meaning: "健康診断", example: "I have a health checkup at the clinic tomorrow morning." },
  { id: "a046", word: "client", meaning: "顧客", example: "Our firm always puts the client's needs first." },
  { id: "a047", word: "colleague", meaning: "同僚", example: "I discussed the project with a colleague from the marketing department." },
  { id: "a048", word: "commend", meaning: "褒める", example: "The manager commended her team for their excellent work on the project." },
  { id: "a049", word: "commute", meaning: "通勤する", example: "He commutes to work by train every day." },
  { id: "a050", word: "compare", meaning: "比較する", example: "We should compare prices before choosing a supplier." },
  { id: "a051", word: "competitor", meaning: "競合他社", example: "Our prices are lower than those of our competitors." },
  { id: "a052", word: "complaint", meaning: "苦情", example: "The customer filed a complaint about the defective product." },
  { id: "a053", word: "complete", meaning: "完了させる", example: "She completed the report just before the deadline." },
  { id: "a054", word: "complicated", meaning: "複雑な", example: "The instructions for assembling the furniture were very complicated." },
  { id: "a055", word: "component", meaning: "部品", example: "Each component of the machine is tested for quality." },
  { id: "a056", word: "concern", meaning: "懸念", example: "Rising costs are a major concern for small businesses." },
  { id: "a057", word: "conduct", meaning: "行う", example: "Our company will conduct a survey to gather customer feedback." },
  { id: "a058", word: "conference", meaning: "会議", example: "I'm attending a medical conference in Tokyo next week." },
  { id: "a059", word: "confirm", meaning: "確認する", example: "Could you confirm the reservation for me by email?" },
  { id: "a060", word: "consult", meaning: "相談する", example: "I need to consult with my supervisor before making a decision." },
  { id: "a061", word: "consumer", meaning: "消費者", example: "Consumers have been spending more on online shopping this year." },
  { id: "a062", word: "contract", meaning: "契約", example: "Make sure you read the entire contract before signing it." },
  { id: "a063", word: "contribute", meaning: "貢献する", example: "Each team member contributed ideas during the brainstorming session." },
  { id: "a064", word: "convenient", meaning: "便利な", example: "Online banking is very convenient because you can use it 24/7." },
  { id: "a065", word: "cuisine", meaning: "料理", example: "We enjoyed authentic Italian cuisine at a famous restaurant in Rome." },
  { id: "a066", word: "current", meaning: "現在の", example: "Our current project is behind schedule due to unforeseen delays." },
  { id: "a067", word: "deadline", meaning: "締め切り", example: "The deadline for the project proposal is next Friday." },
  { id: "a068", word: "decide", meaning: "決定する", example: "We decided to expand our business into Asian markets." },
  { id: "a069", word: "deficit", meaning: "赤字", example: "The company is facing a budget deficit due to unexpected expenses." },
  { id: "a070", word: "delay", meaning: "遅らせる", example: "The train was delayed by 30 minutes because of an accident." },
  { id: "a071", word: "delighted", meaning: "喜んでいる", example: "Our manager was delighted with the successful product launch." },
  { id: "a072", word: "deliver", meaning: "配達する", example: "They can deliver the package to your office by tomorrow." },
  { id: "a073", word: "demand", meaning: "要求する", example: "There is high demand for electric cars in Europe." },
  { id: "a074", word: "department", meaning: "部門", example: "She works in the sales department at headquarters." },
  { id: "a075", word: "designate", meaning: "指名する", example: "The boss designated me as the team leader for this project." },
  { id: "a076", word: "destination", meaning: "目的地", example: "Our flight's destination is Singapore with a stopover in Dubai." },
  { id: "a077", word: "determine", meaning: "決定する", example: "The investigators are trying to determine the cause of the problem." },
  { id: "a078", word: "develop", meaning: "開発する", example: "Our company plans to develop a new smartphone app for customers." },
  { id: "a079", word: "device", meaning: "装置", example: "This device automatically shuts off when it overheats." },
  { id: "a080", word: "discard", meaning: "捨てる", example: "Please discard any old files that we no longer need." },
  { id: "a081", word: "disregard", meaning: "無視する", example: "He disregarded the safety guidelines and got injured." },
  { id: "a082", word: "donate", meaning: "寄付する", example: "She decided to donate part of her bonus to a charity." },
  { id: "a083", word: "durable", meaning: "耐久性のある", example: "This suitcase is made of durable materials that can withstand rough handling." },
  { id: "a084", word: "efficient", meaning: "効率的な", example: "The new software makes our billing process more efficient." },
  { id: "a085", word: "eligible", meaning: "資格のある", example: "Employees are eligible for the bonus after one year of service." },
  { id: "a086", word: "eliminate", meaning: "排除する", example: "We need to eliminate unnecessary expenses to save money." },
  { id: "a087", word: "embarrassing", meaning: "恥ずかしい", example: "It was embarrassing when I forgot my lines during the presentation." },
  { id: "a088", word: "employee", meaning: "従業員", example: "Each employee is given an ID badge to enter the building." },
  { id: "a089", word: "enclose", meaning: "同封する", example: "I have enclosed my résumé with this application email." },
  { id: "a090", word: "encourage", meaning: "奨励する", example: "Our teacher encouraged us to speak English outside the classroom." },
  { id: "a091", word: "endorse", meaning: "支持する", example: "The famous actor endorsed our product in a series of commercials." },
  { id: "a092", word: "enforce", meaning: "施行する", example: "The company will strictly enforce the new dress code policy." },
  { id: "a093", word: "enroll", meaning: "入学する", example: "I decided to enroll in an online English course to improve my skills." },
  { id: "a094", word: "ensure", meaning: "確実にする", example: "Please ensure that all doors are locked before you leave." },
  { id: "a095", word: "enthusiastic", meaning: "熱心な", example: "The team was enthusiastic about the new project idea." },
  { id: "a096", word: "estate", meaning: "財産", example: "He inherited a large estate from his grandfather." },
  { id: "a097", word: "exceed", meaning: "超える", example: "Sales this quarter exceeded our expectations." },
  { id: "a098", word: "except", meaning: "〜を除いて", example: "Everyone is present except the manager, who is on a business trip." },
  { id: "a099", word: "exclusive", meaning: "独占的な", example: "Our company has exclusive rights to distribute that software in Japan." },
  { id: "a100", word: "executive", meaning: "重役", example: "The executives meet every Monday to discuss the company's strategy." },
  { id: "a101", word: "exhibit", meaning: "展示する", example: "Our company will exhibit its new products at the trade show." },
  { id: "a102", word: "expect", meaning: "期待する", example: "We expect to finish the project by the end of the month." },
  { id: "a103", word: "expedite", meaning: "早める", example: "Could you please expedite the shipping of this order? We need it urgently." },
  { id: "a104", word: "expense", meaning: "経費", example: "Travel expenses will be reimbursed by the company." },
  { id: "a105", word: "experience", meaning: "経験する", example: "She has five years of experience in project management." },
  { id: "a106", word: "expertise", meaning: "専門知識", example: "We need someone with technical expertise to solve this problem." },
  { id: "a107", word: "expire", meaning: "期限が切れる", example: "Our lease on the office space expires next month." },
  { id: "a108", word: "explain", meaning: "説明する", example: "Could you explain this chart to me? I don't understand the figures." },
  { id: "a109", word: "extend", meaning: "延長する", example: "They decided to extend the deadline by another week." },
  { id: "a110", word: "facilitate", meaning: "容易にする", example: "His role is to facilitate communication between the teams." },
  { id: "a111", word: "facility", meaning: "施設", example: "The company's new research facility is located in Boston." },
  { id: "a112", word: "fail", meaning: "失敗する", example: "If we fail to deliver on time, we might lose the client's trust." },
  { id: "a113", word: "familiar", meaning: "馴染みのある", example: "I'm not familiar with the new software yet." },
  { id: "a114", word: "fare", meaning: "運賃", example: "The train fare to the airport is about 15 dollars." },
  { id: "a115", word: "feature", meaning: "特徴", example: "The smartphone's new features include a better camera and longer battery life." },
  { id: "a116", word: "fee", meaning: "料金", example: "There is a $50 application fee to apply for the visa." },
  { id: "a117", word: "feedback", meaning: "意見", example: "We received positive feedback from customers about our new service." },
  { id: "a118", word: "figure", meaning: "数字", example: "The sales figures for this quarter look promising." },
  { id: "a119", word: "frequent", meaning: "頻繁な", example: "He is a frequent traveler who flies at least twice a month." },
  { id: "a120", word: "further", meaning: "さらに", example: "If you have any further questions, please feel free to contact me." },
  { id: "a121", word: "hallway", meaning: "廊下", example: "There's a water cooler at the end of the hallway." },
  { id: "a122", word: "handle", meaning: "処理する", example: "She is able to handle multiple projects at the same time." },
  { id: "a123", word: "handout", meaning: "配布資料", example: "The presenter gave everyone a handout summarizing the main points." },
  { id: "a124", word: "host", meaning: "主催する", example: "Our company will host an international conference next year." },
  { id: "a125", word: "identification", meaning: "身分証明", example: "Security checked my identification card at the entrance." },
  { id: "a126", word: "implement", meaning: "実行する", example: "We plan to implement a new training program for employees next month." },
  { id: "a127", word: "improve", meaning: "改善する", example: "The company is trying to improve customer satisfaction by offering better support." },
  { id: "a128", word: "include", meaning: "含む", example: "The price includes breakfast and free internet access." },
  { id: "a129", word: "inconvenience", meaning: "不便", example: "We apologize for the inconvenience caused by the flight delay." },
  { id: "a130", word: "inquire", meaning: "問い合わせる", example: "I would like to inquire about the status of my loan application." },
  { id: "a131", word: "install", meaning: "設置する", example: "They will install the new software on all computers by tomorrow." },
  { id: "a132", word: "instantly", meaning: "即座に", example: "He replied to my email almost instantly." },
  { id: "a133", word: "insurance", meaning: "保険", example: "My health insurance covers annual checkups and vaccinations." },
  { id: "a134", word: "interrupt", meaning: "邪魔する", example: "I'm sorry to interrupt, but you have an urgent call." },
  { id: "a135", word: "inventory", meaning: "在庫", example: "We need to take inventory of the warehouse at the end of the month." },
  { id: "a136", word: "invest", meaning: "投資する", example: "She decided to invest in stocks to save for retirement." },
  { id: "a137", word: "invite", meaning: "招待する", example: "Did you invite Tom to the meeting?" },
  { id: "a138", word: "invoice", meaning: "請求書", example: "They sent us an invoice for last month's consulting services." },
  { id: "a139", word: "involve", meaning: "巻き込む", example: "The project involves many team members from different departments." },
  { id: "a140", word: "issue", meaning: "問題", example: "The main issue we need to discuss is the budget for next year." },
  { id: "a141", word: "itinerary", meaning: "旅行日程", example: "The travel itinerary includes visits to three cities in five days." },
  { id: "a142", word: "justify", meaning: "正当化する", example: "He tried to justify the decision with clear reasoning and data." },
  { id: "a143", word: "launch", meaning: "発売する", example: "The company will launch its new product line in the spring." },
  { id: "a144", word: "locate", meaning: "探し出す", example: "I'm trying to locate a store that sells these parts." },
  { id: "a145", word: "lottery", meaning: "宝くじ", example: "He won a car in a charity lottery." },
  { id: "a146", word: "luggage", meaning: "手荷物", example: "Please keep an eye on your luggage at all times in the airport." },
  { id: "a147", word: "maintain", meaning: "維持する", example: "It's important to maintain good relationships with our clients." },
  { id: "a148", word: "maintenance", meaning: "維持", example: "The copy machine is out of service for maintenance." },
  { id: "a149", word: "manufacture", meaning: "製造する", example: "This factory manufactures car parts for several brands." },
  { id: "a150", word: "miss", meaning: "逃す", example: "I missed the train this morning because I overslept." },
  { id: "a151", word: "modify", meaning: "修正する", example: "We may need to modify the design based on client feedback." },
  { id: "a152", word: "negotiate", meaning: "交渉する", example: "We are negotiating a new contract with the supplier." },
  { id: "a153", word: "notice", meaning: "通知", example: "He gave his two weeks' notice and will leave the company at the end of the month." },
  { id: "a154", word: "notify", meaning: "知らせる", example: "Please notify us immediately if there are any changes to your order." },
  { id: "a155", word: "obliged", meaning: "義務がある", example: "Employees are obliged to follow the company's safety rules at all times." },
  { id: "a156", word: "obtain", meaning: "入手する", example: "You need to obtain a visa before traveling to that country." },
  { id: "a157", word: "offer", meaning: "提供する", example: "They offered me a job after the second interview." },
  { id: "a158", word: "outdated", meaning: "時代遅れの", example: "That software is outdated and no longer supported by the developer." },
  { id: "a159", word: "oversee", meaning: "監督する", example: "He was hired to oversee the project and ensure it finishes on time." },
  { id: "a160", word: "owe", meaning: "借りている", example: "I owe you $20 for the lunch you paid for yesterday." },
  { id: "a161", word: "participate", meaning: "参加する", example: "Employees are encouraged to participate in volunteer activities." },
  { id: "a162", word: "passenger", meaning: "乗客", example: "Each passenger must present a ticket before boarding the train." },
  { id: "a163", word: "pedestrian", meaning: "歩行者", example: "The city built a new bridge for pedestrians to cross the busy road safely." },
  { id: "a164", word: "personnel", meaning: "職員", example: "All company personnel are required to wear ID badges." },
  { id: "a165", word: "plenty", meaning: "たくさんの", example: "Don't rush, we have plenty of time to finish the work." },
  { id: "a166", word: "plumber", meaning: "配管工", example: "We called a plumber to fix the leak in the office kitchen." },
  { id: "a167", word: "policy", meaning: "方針", example: "It is company policy to reply to customer inquiries within 24 hours." },
  { id: "a168", word: "postpone", meaning: "延期する", example: "They decided to postpone the meeting until next week." },
  { id: "a169", word: "premise", meaning: "前提", example: "Our strategy is based on the premise that demand will increase next year." },
  { id: "a170", word: "preservation", meaning: "保存", example: "The museum is dedicated to the preservation of local history." },
  { id: "a171", word: "previous", meaning: "前の", example: "I couldn't attend the meeting because I had a previous engagement." },
  { id: "a172", word: "procedure", meaning: "手順", example: "The safety procedure is clearly outlined in the manual." },
  { id: "a173", word: "proceed", meaning: "進む", example: "You may proceed with the application if you have all the documents ready." },
  { id: "a174", word: "profit", meaning: "利益", example: "Our profits increased by 15% compared to last year." },
  { id: "a175", word: "prohibit", meaning: "禁止する", example: "The company's policy prohibits smoking inside the building." },
  { id: "a176", word: "promote", meaning: "昇進させる", example: "She was promoted to sales manager after only two years at the company." },
  { id: "a177", word: "property", meaning: "財産", example: "They invested in commercial property downtown." },
  { id: "a178", word: "prosperous", meaning: "繁栄した", example: "Thanks to a strong economy, it was a prosperous year for small businesses." },
  { id: "a179", word: "provide", meaning: "提供する", example: "Our company provides technical support 24 hours a day." },
  { id: "a180", word: "publicity", meaning: "宣伝", example: "The celebrity's visit brought a lot of publicity to our store." },
  { id: "a181", word: "purchase", meaning: "購入する", example: "You can purchase tickets online through our website." },
  { id: "a182", word: "pursue", meaning: "追求する", example: "He left the company to pursue his dream of starting his own business." },
  { id: "a183", word: "recognize", meaning: "認識する", example: "The CEO recognized her for her outstanding contribution to the project." },
  { id: "a184", word: "recommend", meaning: "勧める", example: "Can you recommend a good hotel near the conference venue?" },
  { id: "a185", word: "recruit", meaning: "採用する", example: "We need to recruit two new engineers for the development team." },
  { id: "a186", word: "reference", meaning: "参照", example: "She gave her former manager as a reference on her job application." },
  { id: "a187", word: "reflect", meaning: "反映する", example: "The low sales reflect the current economic situation." },
  { id: "a188", word: "refund", meaning: "払い戻す", example: "If you cancel the order, we can issue a full refund." },
  { id: "a189", word: "register", meaning: "登録する", example: "You can register for the workshop online." },
  { id: "a190", word: "regulation", meaning: "規制", example: "New safety regulations require all factories to have fire drills." },
  { id: "a191", word: "reimburse", meaning: "払い戻す", example: "The company will reimburse you for travel expenses." },
  { id: "a192", word: "reliable", meaning: "信頼できる", example: "We need a reliable supplier who can deliver on time." },
  { id: "a193", word: "relief", meaning: "安心", example: "It was a relief to hear that no one was injured in the accident." },
  { id: "a194", word: "remind", meaning: "思い出させる", example: "This email is to remind you about your appointment tomorrow." },
  { id: "a195", word: "remove", meaning: "取り除く", example: "Please remove your shoes before entering the meeting room." },
  { id: "a196", word: "replace", meaning: "交換する", example: "We need to replace the printer ink cartridge; it's almost empty." },
  { id: "a197", word: "replacement", meaning: "交換", example: "Our manager is on maternity leave, so we hired a temporary replacement." },
  { id: "a198", word: "representative", meaning: "代表者", example: "A sales representative will visit our office to show us the new products." },
  { id: "a199", word: "require", meaning: "要求する", example: "This job requires strong communication skills." },
  { id: "a200", word: "reservation", meaning: "予約", example: "I made a reservation for two at the Italian restaurant." },
  { id: "a201", word: "reserve", meaning: "予約する", example: "We need to reserve a conference room for Friday's meeting." },
  { id: "a202", word: "responsible", meaning: "責任がある", example: "He is responsible for training new employees." },
  { id: "a203", word: "result", meaning: "結果", example: "The results of the survey will be published next week." },
  { id: "a204", word: "retail", meaning: "小売", example: "She works in retail and deals with customers every day." },
  { id: "a205", word: "retrieve", meaning: "取り戻す", example: "I went back to the office to retrieve a file I had forgotten." },
  { id: "a206", word: "revenue", meaning: "収益", example: "Our advertising revenue increased by 20% this year." },
  { id: "a207", word: "review", meaning: "見直す", example: "Please review the document and let me know if you find any errors." },
  { id: "a208", word: "severe", meaning: "厳しい", example: "There is a severe shortage of water in this region due to the drought." },
  { id: "a209", word: "shipment", meaning: "出荷", example: "The shipment of new computers arrived at the warehouse yesterday." },
  { id: "a210", word: "shopper", meaning: "買い物客", example: "The mall was crowded with holiday shoppers looking for gifts." },
  { id: "a211", word: "shortage", meaning: "不足", example: "The factory had to slow production due to a shortage of raw materials." },
  { id: "a212", word: "solution", meaning: "解決策", example: "We need to find a solution to the problem of late deliveries." },
  { id: "a213", word: "souvenir", meaning: "お土産", example: "I bought a mug as a souvenir of my trip to New York." },
  { id: "a214", word: "store", meaning: "保管する", example: "Important documents are stored in a secure cabinet." },
  { id: "a215", word: "strategy", meaning: "戦略", example: "Our marketing strategy for next year focuses on social media advertising." },
  { id: "a216", word: "stroll", meaning: "散歩する", example: "After dinner, we took a leisurely stroll through the park." },
  { id: "a217", word: "subsidiary", meaning: "子会社", example: "ABC Electronics is a subsidiary of a large international company." },
  { id: "a218", word: "substitute", meaning: "代用する", example: "Mr. Tanaka will substitute for me at tomorrow's meeting." },
  { id: "a219", word: "superb", meaning: "素晴らしい", example: "She gave a superb presentation that impressed everyone." },
  { id: "a220", word: "supplement", meaning: "補足", example: "He works part-time in the evenings to supplement his income." },
  { id: "a221", word: "supplier", meaning: "納入業者", example: "We switched to a new supplier to get better quality materials." },
  { id: "a222", word: "surpass", meaning: "上回る", example: "Our sales this year surpassed last year's by 30%." },
  { id: "a223", word: "suspicion", meaning: "疑い", example: "The manager's unexplained absences raised suspicion among the staff." },
  { id: "a224", word: "survey", meaning: "調査", example: "We conducted a survey to find out how customers feel about our service." },
  { id: "a225", word: "swiftly", meaning: "素早く", example: "The issue was swiftly resolved by the technical team." },
  { id: "a226", word: "tolerate", meaning: "我慢する", example: "Our company does not tolerate discrimination of any kind." },
  { id: "a227", word: "transaction", meaning: "取引", example: "Each credit card transaction is recorded in the database." },
  { id: "a228", word: "transfer", meaning: "移す", example: "She was transferred to the London office last year." },
  { id: "a229", word: "transparent", meaning: "透明な", example: "We try to be transparent about our pricing with our customers." },
  { id: "a230", word: "transportation", meaning: "輸送", example: "Public transportation is very convenient in Tokyo." },
  { id: "a231", word: "tuition", meaning: "授業料", example: "He is working part-time to pay for his college tuition." },
  { id: "a232", word: "turbulent", meaning: "荒れ狂う", example: "We experienced some turbulent weather during the flight." },
  { id: "a233", word: "turnout", meaning: "出席者数", example: "The turnout at the annual meeting was higher than expected." },
  { id: "a234", word: "unanimous", meaning: "満場一致の", example: "The board made a unanimous decision to hire the new CEO." },
  { id: "a235", word: "unearth", meaning: "発掘する", example: "The investigation unearthed evidence of financial wrongdoing." },
  { id: "a236", word: "utensil", meaning: "用具", example: "Please put the cooking utensils in that drawer." },
  { id: "a237", word: "utilization", meaning: "利用", example: "We need to improve the utilization of our resources during peak periods." },
  { id: "a238", word: "vacant", meaning: "空いている", example: "The position of assistant manager is currently vacant." },
  { id: "a239", word: "valid", meaning: "有効な", example: "Your ticket is valid for two days after purchase." },
  { id: "a240", word: "vendor", meaning: "販売業者", example: "We buy office supplies from a local vendor to support small businesses." },
  { id: "a241", word: "venue", meaning: "会場", example: "The venue for the conference will be the Grand Hotel downtown." },
  { id: "a242", word: "voucher", meaning: "クーポン券", example: "I have a voucher for a free coffee at that café." },
  { id: "a243", word: "warehouse", meaning: "倉庫", example: "The products are stored in a warehouse outside the city." },
  { id: "a244", word: "warning", meaning: "警告", example: "He ignored the warning about the slippery floor and almost fell." },
  { id: "a245", word: "warranty", meaning: "保証書", example: "The laptop comes with a one-year warranty." },
  { id: "a246", word: "welfare", meaning: "福祉", example: "The company's new policy shows concern for employee welfare." },
  { id: "a247", word: "wholesale", meaning: "卸売", example: "They purchase goods at wholesale prices and sell them at retail." },
  { id: "a248", word: "withstand", meaning: "耐える", example: "This material can withstand high temperatures without melting." },
  { id: "a249", word: "workplace", meaning: "職場", example: "Maintaining a clean workplace helps improve productivity." },
  { id: "a250", word: "workshop", meaning: "研修会", example: "Our team attended a workshop on effective communication skills." }
];

const passageData = [
  {
    id: "p001",
    title: "Notice to Employees",
    text: "Please be advised that the company will (____) a new security system starting next Monday. All employees must carry their ID badges at all times.",
    targetId: "a126", // implement
    questions: [
      { type: "vocab", q: "空所に最適な語は？", options: ["implement", "fluctuate", "brief", "terminate"], ans: "implement" },
      { type: "content", q: "通知の内容は？", options: ["セキュリティ導入", "休日案内", "清掃案内", "給与改定"], ans: "セキュリティ導入" }
    ]
  },
  {
    id: "p002",
    title: "Reservation",
    text: "The grand ballroom can (____) up to 200 guests. Please confirm your guest list.",
    targetId: "a001", // accommodate
    questions: [
      { type: "vocab", q: "空所に最適な語は？", options: ["eliminate", "accommodate", "adhere", "fluctuate"], ans: "accommodate" },
      { type: "content", q: "最大人数は？", options: ["50名", "100名", "200名", "500名"], ans: "200名" }
    ]
  }
];
// 追加分 a251-a350 を window.wordData の末尾にコピペして足す用
// 形式: { id, word, meaning, example, example_jp }

const moreWordData = [
  { id: "a251", word: "achieve", meaning: "達成する", example: "We achieved our sales target ahead of schedule.", example_jp: "私たちは予定より早く売上目標を達成した．" },
  { id: "a252", word: "acknowledge", meaning: "認める", example: "Please acknowledge receipt of this email.", example_jp: "このメールを受け取ったことを確認してほしい．" },
  { id: "a253", word: "adjust", meaning: "調整する", example: "We need to adjust the budget for next quarter.", example_jp: "次の四半期に向けて予算を調整する必要がある．" },
  { id: "a254", word: "adopt", meaning: "採用する", example: "The company adopted a new remote work policy.", example_jp: "その会社は新しい在宅勤務方針を採用した．" },
  { id: "a255", word: "advise", meaning: "助言する", example: "Our lawyer advised us to review the contract carefully.", example_jp: "弁護士は契約書を慎重に確認するよう助言した．" },
  { id: "a256", word: "affect", meaning: "影響する", example: "The delay may affect the delivery date.", example_jp: "その遅れは納期に影響するかもしれない．" },
  { id: "a257", word: "agree", meaning: "同意する", example: "All members agreed on the final plan.", example_jp: "全員が最終案に同意した．" },
  { id: "a258", word: "aim", meaning: "目的とする", example: "This campaign aims to increase brand awareness.", example_jp: "このキャンペーンは認知度向上を目的としている．" },
  { id: "a259", word: "announce", meaning: "発表する", example: "The CEO announced the new partnership today.", example_jp: "CEOは本日新しい提携を発表した．" },
  { id: "a260", word: "approve", meaning: "承認する", example: "The manager approved my vacation request.", example_jp: "上司は休暇申請を承認した．" },

  { id: "a261", word: "arrange", meaning: "手配する", example: "I arranged a meeting with the client.", example_jp: "顧客との会議を手配した．" },
  { id: "a262", word: "assist", meaning: "手伝う", example: "Could you assist me with this report?", example_jp: "このレポートを手伝ってくれないか．" },
  { id: "a263", word: "available", meaning: "利用可能な", example: "The product will be available next month.", example_jp: "その製品は来月利用可能になる．" },
  { id: "a264", word: "aware", meaning: "気付いている", example: "Are you aware of the updated rules?", example_jp: "更新された規則を把握しているか．" },
  { id: "a265", word: "balance", meaning: "均衡,残高", example: "Please check your account balance online.", example_jp: "オンラインで口座残高を確認してほしい．" },
  { id: "a266", word: "bill", meaning: "請求書", example: "The vendor sent us the bill yesterday.", example_jp: "業者が昨日請求書を送ってきた．" },
  { id: "a267", word: "bonus", meaning: "賞与", example: "Employees receive a bonus based on performance.", example_jp: "従業員は成績に応じて賞与を受け取る．" },
  { id: "a268", word: "brief", meaning: "簡潔な", example: "Keep your presentation brief and clear.", example_jp: "発表は簡潔で分かりやすくしてほしい．" },
  { id: "a269", word: "cancel", meaning: "取り消す", example: "We had to cancel the order due to an error.", example_jp: "誤りのため注文を取り消さなければならなかった．" },
  { id: "a270", word: "charge", meaning: "料金を請求する", example: "They charge a fee for express delivery.", example_jp: "速達配送には料金がかかる．" },

  { id: "a271", word: "clarify", meaning: "明確にする", example: "Could you clarify what you mean by that?", example_jp: "それがどういう意味か明確にしてほしい．" },
  { id: "a272", word: "collect", meaning: "集める", example: "We collected feedback from customers.", example_jp: "顧客からフィードバックを集めた．" },
  { id: "a273", word: "commit", meaning: "約束する,専念する", example: "We are committed to improving quality.", example_jp: "私たちは品質向上に取り組むことを約束している．" },
  { id: "a274", word: "communicate", meaning: "伝える", example: "Please communicate the change to the team.", example_jp: "変更点をチームに伝えてほしい．" },
  { id: "a275", word: "confirm", meaning: "確認する", example: "I called to confirm the reservation.", example_jp: "予約を確認するために電話した．" },
  { id: "a276", word: "consider", meaning: "検討する", example: "We will consider your proposal carefully.", example_jp: "提案を慎重に検討する．" },
  { id: "a277", word: "contact", meaning: "連絡する", example: "Contact us if you need assistance.", example_jp: "支援が必要なら連絡してほしい．" },
  { id: "a278", word: "continue", meaning: "続ける", example: "The service will continue without interruption.", example_jp: "サービスは中断なく継続される．" },
  { id: "a279", word: "cooperate", meaning: "協力する", example: "All departments must cooperate on this project.", example_jp: "全ての部門がこのプロジェクトに協力しなければならない．" },
  { id: "a280", word: "cost", meaning: "費用がかかる", example: "It will cost less if we buy in bulk.", example_jp: "まとめ買いすれば費用は少なくなる．" },

  { id: "a281", word: "create", meaning: "作成する", example: "She created a detailed schedule for the event.", example_jp: "彼女はイベントの詳細な予定表を作成した．" },
  { id: "a282", word: "decrease", meaning: "減少する", example: "Expenses decreased after the new policy started.", example_jp: "新しい方針開始後に経費が減少した．" },
  { id: "a283", word: "dedicate", meaning: "専念する", example: "He dedicated his time to customer support.", example_jp: "彼は顧客対応に時間を専念した．" },
  { id: "a284", word: "define", meaning: "定義する", example: "We need to define the scope of the project.", example_jp: "プロジェクトの範囲を定義する必要がある．" },
  { id: "a285", word: "deliver", meaning: "届ける", example: "The courier delivered the documents by noon.", example_jp: "配達員が正午までに書類を届けた．" },
  { id: "a286", word: "demonstrate", meaning: "実演する,示す", example: "She demonstrated how the software works.", example_jp: "彼女はソフトの使い方を実演した．" },
  { id: "a287", word: "department", meaning: "部門", example: "Please forward this to the HR department.", example_jp: "これを人事部に転送してほしい．" },
  { id: "a288", word: "discuss", meaning: "話し合う", example: "We discussed the issue during the meeting.", example_jp: "会議でその問題を話し合った．" },
  { id: "a289", word: "display", meaning: "表示する", example: "The screen displays the final total.", example_jp: "画面に合計金額が表示される．" },
  { id: "a290", word: "distribute", meaning: "配布する", example: "They distributed flyers at the station.", example_jp: "駅でチラシを配布した．" },

  { id: "a291", word: "efficient", meaning: "効率的な", example: "This workflow is more efficient than the old one.", example_jp: "この手順は以前より効率的だ．" },
  { id: "a292", word: "enable", meaning: "可能にする", example: "This feature enables faster search.", example_jp: "この機能により検索が速くなる．" },
  { id: "a293", word: "encounter", meaning: "遭遇する", example: "We encountered an unexpected problem.", example_jp: "予期しない問題に遭遇した．" },
  { id: "a294", word: "estimate", meaning: "見積もる", example: "Can you estimate the total cost?", example_jp: "総費用を見積もれるか．" },
  { id: "a295", word: "evaluate", meaning: "評価する", example: "We evaluated several options before deciding.", example_jp: "決定前に複数案を評価した．" },
  { id: "a296", word: "expand", meaning: "拡大する", example: "The company plans to expand into new markets.", example_jp: "その会社は新市場へ拡大する計画だ．" },
  { id: "a297", word: "explain", meaning: "説明する", example: "He explained the procedure step by step.", example_jp: "彼は手順を段階的に説明した．" },
  { id: "a298", word: "finalize", meaning: "最終決定する", example: "We finalized the design last night.", example_jp: "昨夜デザインを最終決定した．" },
  { id: "a299", word: "focus", meaning: "集中する", example: "Let's focus on the most urgent tasks first.", example_jp: "まず最も緊急の作業に集中しよう．" },
  { id: "a300", word: "forecast", meaning: "予測", example: "The forecast shows higher demand next month.", example_jp: "予測では来月需要が増える．" },

  { id: "a301", word: "gather", meaning: "集める", example: "We gathered data from multiple sources.", example_jp: "複数の情報源からデータを集めた．" },
  { id: "a302", word: "generate", meaning: "生み出す", example: "This campaign generated many new leads.", example_jp: "この施策で多くの新規見込み客が生まれた．" },
  { id: "a303", word: "guarantee", meaning: "保証する", example: "We guarantee a full refund within 30 days.", example_jp: "30日以内なら全額返金を保証する．" },
  { id: "a304", word: "handle", meaning: "対応する", example: "She can handle difficult customers calmly.", example_jp: "彼女は難しい客にも落ち着いて対応できる．" },
  { id: "a305", word: "hire", meaning: "雇う", example: "The company hired two new engineers.", example_jp: "会社は新しい技術者を2人雇った．" },
  { id: "a306", word: "immediately", meaning: "直ちに", example: "Please reply immediately if you see this.", example_jp: "これを見たら直ちに返信してほしい．" },
  { id: "a307", word: "improve", meaning: "改善する", example: "We improved the interface to reduce errors.", example_jp: "ミスを減らすために画面を改善した．" },
  { id: "a308", word: "increase", meaning: "増加する", example: "Prices may increase due to higher costs.", example_jp: "コスト増で価格が上がるかもしれない．" },
  { id: "a309", word: "inform", meaning: "知らせる", example: "Please inform all staff of the new schedule.", example_jp: "新しい予定を全員に知らせてほしい．" },
  { id: "a310", word: "install", meaning: "導入する", example: "They installed a new security camera system.", example_jp: "新しい防犯カメラを導入した．" },

  { id: "a311", word: "issue", meaning: "問題", example: "We need to resolve the issue quickly.", example_jp: "その問題を早く解決する必要がある．" },
  { id: "a312", word: "maintain", meaning: "維持する", example: "Maintain a clean workspace at all times.", example_jp: "常に作業場所を清潔に維持してほしい．" },
  { id: "a313", word: "manage", meaning: "管理する", example: "He manages a team of five people.", example_jp: "彼は5人のチームを管理している．" },
  { id: "a314", word: "measure", meaning: "測定する", example: "We measured customer satisfaction last month.", example_jp: "先月顧客満足度を測定した．" },
  { id: "a315", word: "mention", meaning: "言及する", example: "She mentioned the deadline during the call.", example_jp: "彼女は電話で締切に言及した．" },
  { id: "a316", word: "monitor", meaning: "監視する", example: "We monitor system performance in real time.", example_jp: "システム性能をリアルタイムで監視している．" },
  { id: "a317", word: "notify", meaning: "通知する", example: "Notify the supervisor if any errors occur.", example_jp: "エラーが起きたら上司に通知してほしい．" },
  { id: "a318", word: "operate", meaning: "運用する", example: "This machine is easy to operate.", example_jp: "この機械は操作しやすい．" },
  { id: "a319", word: "organize", meaning: "整理する", example: "We organized the files by date.", example_jp: "日付ごとにファイルを整理した．" },
  { id: "a320", word: "participate", meaning: "参加する", example: "Many employees participated in the training.", example_jp: "多くの従業員が研修に参加した．" },

  { id: "a321", word: "perform", meaning: "実行する", example: "The team performed a final quality check.", example_jp: "チームは最終品質確認を実施した．" },
  { id: "a322", word: "prepare", meaning: "準備する", example: "Please prepare the documents by Friday.", example_jp: "金曜までに書類を準備してほしい．" },
  { id: "a323", word: "prevent", meaning: "防ぐ", example: "Strong passwords help prevent data leaks.", example_jp: "強いパスワードは情報漏えいを防ぐ．" },
  { id: "a324", word: "priority", meaning: "優先事項", example: "Safety is our top priority.", example_jp: "安全が最優先事項だ．" },
  { id: "a325", word: "process", meaning: "処理する", example: "We processed the refund within 24 hours.", example_jp: "24時間以内に返金処理をした．" },
  { id: "a326", word: "purchase", meaning: "購入する", example: "You can purchase the ticket online.", example_jp: "チケットはオンラインで購入できる．" },
  { id: "a327", word: "recommend", meaning: "勧める", example: "I recommend updating the software.", example_jp: "ソフト更新を勧める．" },
  { id: "a328", word: "reduce", meaning: "減らす", example: "We reduced costs by switching suppliers.", example_jp: "業者を変えてコストを減らした．" },
  { id: "a329", word: "replace", meaning: "交換する", example: "Replace the battery when the light turns red.", example_jp: "ランプが赤になったら電池を交換してほしい．" },
  { id: "a330", word: "request", meaning: "依頼する", example: "She requested additional information.", example_jp: "彼女は追加情報を依頼した．" },

  { id: "a331", word: "require", meaning: "必要とする", example: "This job requires strong communication skills.", example_jp: "この仕事には高いコミュ力が必要だ．" },
  { id: "a332", word: "respond", meaning: "対応する", example: "We responded to the complaint promptly.", example_jp: "苦情に迅速に対応した．" },
  { id: "a333", word: "schedule", meaning: "予定を組む", example: "We scheduled the interview for Monday.", example_jp: "面接を月曜に予定した．" },
  { id: "a334", word: "select", meaning: "選ぶ", example: "Select the plan that fits your needs.", example_jp: "要件に合うプランを選んでほしい．" },
  { id: "a335", word: "send", meaning: "送る", example: "I sent the file as an attachment.", example_jp: "ファイルを添付で送った．" },
  { id: "a336", word: "share", meaning: "共有する", example: "Please share the link with the team.", example_jp: "リンクをチームに共有してほしい．" },
  { id: "a337", word: "solve", meaning: "解決する", example: "We solved the problem after several tests.", example_jp: "何度か試験して問題を解決した．" },
  { id: "a338", word: "submit", meaning: "提出する", example: "Submit the form by the deadline.", example_jp: "締切までに書類を提出してほしい．" },
  { id: "a339", word: "support", meaning: "支援する", example: "Our staff will support you during setup.", example_jp: "設定中はスタッフが支援する．" },
  { id: "a340", word: "update", meaning: "更新する", example: "Update the app to the latest version.", example_jp: "アプリを最新版に更新してほしい．" },

  { id: "a341", word: "verify", meaning: "確認する", example: "We verified the details with the client.", example_jp: "顧客と詳細を確認した．" },
  { id: "a342", word: "warn", meaning: "警告する", example: "The sign warns visitors about the wet floor.", example_jp: "看板が床が濡れていると来訪者に警告している．" },
  { id: "a343", word: "within", meaning: "以内に", example: "We will reply within two business days.", example_jp: "2営業日以内に返信する．" },
  { id: "a344", word: "withdraw", meaning: "引き出す", example: "You can withdraw cash from this ATM.", example_jp: "このATMで現金を引き出せる．" },
  { id: "a345", word: "witness", meaning: "目撃者", example: "A witness reported the accident to the police.", example_jp: "目撃者が事故を警察に通報した．" },
  { id: "a346", word: "arrive", meaning: "到着する", example: "The shipment arrived earlier than expected.", example_jp: "出荷品は予想より早く到着した．" },
  { id: "a347", word: "departure", meaning: "出発", example: "Please check the departure time on the ticket.", example_jp: "チケットで出発時刻を確認してほしい．" },
  { id: "a348", word: "extend", meaning: "延長する", example: "They extended the warranty for an extra year.", example_jp: "保証を1年延長した．" },
  { id: "a349", word: "recommendation", meaning: "推薦,推奨", example: "Thank you for your recommendation letter.", example_jp: "推薦状をありがとう．" },
  { id: "a350", word: "responsibility", meaning: "責任", example: "It is my responsibility to report the results.", example_jp: "結果を報告するのは私の責任だ．" }
];

// 使い方: data.js の最後にこれを貼ってから
// window.wordData = window.wordData.concat(moreWordData);